from decimal import Rounded
import tkinter as tk
from tkinter import Place, ttk
#GregTech Fusion Reactor to Plasma Turbine Ratio Calculator
#Made by Minecrafrpro2039

#This calculator allows you to select a fusion reactor recipe, a plasma turbine recipe, a turbine rotor, and a rotor holder tie
#to calculate the amount of plasma turbines needed to consume the plasma output of the fusion reactors and the total EU generated by the plasma turbines.

#Reactor_recipe class is Plasma output, Plasma output amount, Reactor input 1,
#Reactor input 1 amount, Reactor input 2, Reactor input 2 amount, 
#Duration, Total EU, EU per tick
class Reactor_recipe:
    def __init__(self, Plasma_type1, Plasma_type1_output,
                 Reactor_Input1, Reactor_input1_amount,
                 Reactor_input2, Reactor_input2_amount,
                 Reactor_duration, Reactor_total_eu, Reactor_eu_usage_per_tick, Reactor_recipe_voltage_tier):
        
        self.base_output_amount = Plasma_type1_output
        self.base_input1_amount = Reactor_input1_amount
        self.base_input2_amount = Reactor_input2_amount
        self.Reactor_duration = Reactor_duration
        self.Reactor_total_eu = Reactor_total_eu
        self.Reactor_eu_usage_per_tick = Reactor_eu_usage_per_tick
        self.Reactor_recipe_voltage_tier = Reactor_recipe_voltage_tier

        self.Reactor_output = Plasma_type1
        self.Reactor_input1 = Reactor_Input1
        self.Reactor_input2 = Reactor_input2

    def format(self, reactor_amount):
        return (
            f"Reactor output: {self.Reactor_output} - {(self.base_output_amount / self.Reactor_duration)/20 * reactor_amount} mB/tick\n"
            f"Reactor input 1: {self.Reactor_input1} - {(self.base_input1_amount / self.Reactor_duration)/20 * reactor_amount} mB/tick\n"
            f"Reactor input 2: {self.Reactor_input2} - {(self.base_input2_amount / self.Reactor_duration)/20 * reactor_amount} mB/tick\n\n"
            f"Reactor Duration: {self.Reactor_duration} s\n"
            f"Reactor Total EU: {self.Reactor_total_eu * reactor_amount}\n"
            f"Reactor EU per Tick: {self.Reactor_eu_usage_per_tick * reactor_amount} EU/t"
    )

#Plasma_recipe class is Plasma input, Plasma input amount, Liquid output, 
#Liquid output amount, Duration, Total EU, EU per tick
class Plasma_recipe:
    def __init__(self, Plasma_type1, Plasma_type1_input, 
                 Liquid_type1, Liquid_type1_output,
                 Plasma_turbine_Duration, Plasma_turbine_total_eu, Plasma_turbine_eu_per_tick):
        self.Plasma_type1 = Plasma_type1
        self.Plasma_type1_input = Plasma_type1_input
        self.Liquid_type1 = Liquid_type1
        self.Liquid_type1_output = Liquid_type1_output
        self.Plasma_turbine_Duration = Plasma_turbine_Duration
        self.Plasma_turbine_total_eu = Plasma_turbine_total_eu
        self.Plasma_turbine_eu_per_tick = Plasma_turbine_eu_per_tick

    def format(self):
        return (
            f"Plasma input: {self.Plasma_type1} - {self.Plasma_type1_input} mB\n"
            f"Liquid output: {self.Liquid_type1} - {self.Liquid_type1_output} mB\n"
            f"Plasma Turbine Duration: {self.Plasma_turbine_Duration} s\n"
            f"Plasma Turbine Total EU: {self.Plasma_turbine_total_eu}\n"
            f"Plasma Turbine EU per Tick: {self.Plasma_turbine_eu_per_tick} EU/tick"
        )
    
#Rotor class is Rotor type, Rotor efficiency, Rotor power
class Rotor:
    def __init__(self, Rotor_type, Rotor_efficiency, Rotor_Power):
        self.Rotor_type = Rotor_type
        self.Rotor_efficiency = Rotor_efficiency
        self.Rotor_Power = Rotor_Power

#Rotor tier is Tier name, Tier multiplier Efficiency multiplier
class Rotor_hatch_tier:
    def __init__(self, Tier_name, Tier_multiplier, Eu_multiplier):
        self.Tier_name = Tier_name
        self.Tier_multiplier = Tier_multiplier
        self.Eu_multiplier = Eu_multiplier

#PlasmaTurbineCalculator class is 
#Rotor efficiency, Rotor Power, Tier multiplier,
#Eu multiplier, Plasma turbine duration, Reactor output,
#Liquid type 1 output, Reactor duration
class PlasmaTurbineCalculator:
    Base_eu = 2048
    Base_Parallels = 8

    def __init__(self, Rotor_efficiency, Rotor_Power, Tier_multiplier, Eu_multiplier, Plasma_turbine_duration, Reactor_output, Liquid_type1_output, Reactor_duration):
        self.Rotor_efficiency = Rotor_efficiency
        self.Rotor_Power = Rotor_Power
        self.Tier_multiplier = Tier_multiplier
        self.Eu_multiplier = Eu_multiplier
        self.Plasma_turbine_duration = Plasma_turbine_duration
        self.Reactor_output = Reactor_output
        self.Liquid_type1_output = Liquid_type1_output
        self.Reactor_duration = Reactor_duration

    def parallels(self):
        return (
            self.Base_Parallels * (self.Rotor_Power / 100) * self.Eu_multiplier
        )

    def efficiency(self):
        return (
            (self.Rotor_efficiency * self.Tier_multiplier)
        )

    def eu_per_tick(self):
        return (
            self.Base_eu * self.parallels()
        )
    
    def Recipe_time(self):
        return (
            (self.efficiency() * self.Plasma_turbine_duration)/100
        )
    
    def Reactor_to_turbine_ratio(self):
        return(
            ((self.Reactor_output / self.Reactor_duration) /
             (((self.Liquid_type1_output * self.parallels())
                / self.Recipe_time()))
            )
        )
    
def voltage_tiers(Tier_name, value):
    return Tier_name, value

#Voltage tiers... 
Volatage_Tiers = [
    voltage_tiers("Ulv", 1),
    voltage_tiers("Lv", 2),
    voltage_tiers("Mv", 3),
    voltage_tiers("Hv", 4),
    voltage_tiers("Ev", 5),
    voltage_tiers("Iv", 6),
    voltage_tiers("LuV", 7),
    voltage_tiers("Zpm", 8),
    voltage_tiers("Uv", 9),
    voltage_tiers("UHV", 10),
    voltage_tiers("UEV", 11),
    voltage_tiers("UIV", 12),

]

#Fusion Reactor recipes are Plasma output, Plasma output amount, Reactor input 1, Reactor input 1 amount, Reactor input 2, Reactor input 2 amount, Duration, Total EU, EU per tick
Fusion_reactor_Recipes = [
    Reactor_recipe("Nickel Plasma", 144, "Liquid Potassium", 144, "Fluorine Gas", 1000, 7.2, 4423680, 30720, 7),
    Reactor_recipe("Helium Plasma", 1000, "Deuterium Gas", 1000, "Tritium Gas", 1000, 4, 589824, 4096, 6),
    Reactor_recipe("Tin Plasma", 144, "Liquid Silver", 144, "Helium 3", 1500, 8.4, 3538944, 24576, 7),
    Reactor_recipe("Nitrogen Plasma", 100, "Liquid Beryllium", 144, "Deuterium Gas", 3000, 7.2, 2359296, 16384, 7),
    Reactor_recipe("Oxygen Plasma", 1000, "Liquid Carbon", 144, "Helium 3", 1000, 12.8, 1048576, 4096, 6),
    Reactor_recipe("Iron Plasma", 144, "Liquid Silicon", 144, "Liquid Magnesium", 144, 10.8, 1658880, 7680, 7),
    Reactor_recipe("Argon Plasma", 1000, "Liquid Carbon", 144, "Liquid Manganese", 144, 7.2, 3533944, 24576, 7),
    Reactor_recipe("Americium Plasma", 144, "Liquid Plutonium 241", 144, "Hydrogen Gas", 1000, 15.6, 30670840, 98304, 8),
    Reactor_recipe("Magmatic Plasma", 144, "Infernal Concentrate", 500, "Iron Plasma", 288, 12.8, 17066496, 66666, 8),
]

#Plasma Turbine recpies are Plasma input, Liquid output, Duration, Total EU, EU per tick
Plasma_turbine_Recipes = [
    Plasma_recipe("Nickel Plasma", 1, "Liquid Nickel", 1, 9.6, 393216, 2048),
    Plasma_recipe("Helium Plasma", 5, "Liquid Helium", 5, 2.7, 110592, 2048),
    Plasma_recipe("Tin Plasma", 1, "Liquid Tin", 1, 8.4, 344064, 2048),
    Plasma_recipe("Nitrogen Plasma", 5, "Liquid Nitrogen", 5, 5.4, 221184, 2048),
    Plasma_recipe("Oxygen Plasma", 5, "Liquid Oxygen", 5, 5.4, 221184, 2048),
    Plasma_recipe("Iron Plasma", 1, "Liquid Iron", 1, 6.75, 276480, 2048),
    Plasma_recipe("Argon Plasma", 5, "Liquid Argon", 5, 6.3, 258048, 2048),
    Plasma_recipe("Americium Plasma", 1, "Liquid Americium", 1, 33.8, 1384448, 2048),
    Plasma_recipe("Magmatic Plasma", 1, "Infernal Concentrate", 1, 56.9, 2330624, 2048),
]

#Trubine rotors are Name, Efficiency, Power
#Turbine Rotor efficiency Multiplies Parrallel ex: 110% = 1.1x, 170% = 1.7x
#Turbine Rotor Power muiltiplies parallels
Turbine_rotor = [
    Rotor("Twinite Turbine Rotor", 260, 700),
    Rotor("Dragonsteel Turbine Rotor", 380, 1100),
    Rotor("Prismalium Turbine Rotor", 470, 1600),
    Rotor("Melodium Turbine Rotor", 550, 2000),
    Rotor("Stellarium Turbine Rotor", 660, 3200)
]

#Rotor tiers are Name, Multiplier
#Rotor holder tier efficiency multipler increases the rotor efficiency by 10% per tier
#rotor holder tier mulitply the Eu per tick by 2 per tier
Turbine_rotor_holder_tiers = [
    Rotor_hatch_tier("IV", 1.0, 1),
    Rotor_hatch_tier("LuV", 1.1, 2),
    Rotor_hatch_tier("ZPM", 1.2, 4),
    Rotor_hatch_tier("UV", 1.3, 8),
    Rotor_hatch_tier("UHV", 1.4, 16),
    Rotor_hatch_tier("UEV", 1.5, 32),
    Rotor_hatch_tier("UIV", 1.6, 64),
]

Plasma_turbine_lookup = {r.Plasma_type1: r for r in Plasma_turbine_Recipes}
Rotor_lookup = {r.Rotor_type: r for r in Turbine_rotor}
Tier_lookup = {t.Tier_name: t for t in Turbine_rotor_holder_tiers}

def update_display(*_):
    reactors = reactor_amount.get()
    overclock = Overclock_voltage.get()
    
    # Calculate overclock divisor (each level divides duration in half)
    overclock_divisor = 2 ** overclock if overclock > 0 else 1

    rotor = Rotor_lookup[Turbine_rotor_box.get()]
    tier = Tier_lookup[Rotor_holder_box.get()]
    turbine_recipe = Plasma_turbine_lookup[Plasma_turbine_recipe_box.get()]

    reactor_recipe = next(
        r for r in Fusion_reactor_Recipes
        if r.Reactor_output == turbine_recipe.Plasma_type1
    )
    
    # Update voltage tier label
    voltage_tier_label.config(text=f"Reactor Recipe Voltage Tier: {Volatage_Tiers[reactor_recipe.Reactor_recipe_voltage_tier - 1][0]}")

    calc = PlasmaTurbineCalculator(
        Rotor_efficiency=rotor.Rotor_efficiency,
        Rotor_Power=rotor.Rotor_Power,
        Tier_multiplier=tier.Tier_multiplier,
        Eu_multiplier=tier.Eu_multiplier,
        Plasma_turbine_duration=turbine_recipe.Plasma_turbine_Duration,
        Reactor_output=reactor_recipe.base_output_amount * reactors,
        Liquid_type1_output=turbine_recipe.Liquid_type1_output,
        Reactor_duration=reactor_recipe.Reactor_duration / overclock_divisor
    )

    #Reactor output display
    reactor_output_box.config(state="normal")
    reactor_output_box.delete("1.0", tk.END)
    reactor_output_box.insert(
        tk.END,
        reactor_recipe.format(reactors)
    )
    reactor_output_box.config(state="disabled")

    #Turbine output display
    R_to_T = int(calc.Reactor_to_turbine_ratio())
    turbine_output_box.config(state="normal")
    turbine_output_box.delete("1.0", tk.END)
    turbine_output_box.insert(
        tk.END,
        f"Plasma Turbine Recipe: {turbine_recipe.Plasma_type1}\n"
        f"Plasma Turbine Input: {turbine_recipe.Plasma_type1} - {turbine_recipe.Plasma_type1_input * calc.parallels():.5f} mB\n"
        f"Plasma Turbine Output: {turbine_recipe.Liquid_type1} - {turbine_recipe.Liquid_type1_output * calc.parallels():.5f} mB\n"
        f"Rotor: {rotor.Rotor_type}\n"
        f"Rotor Holder Tier: {tier.Tier_name}\n"
        f"Total Amount of Plasma Turbines: {R_to_T}\n\n"
        f"Parallels: {calc.parallels():.5f}\n"
        f"Efficiency: {calc.efficiency():.5f} %\n"
        f"EU per Tick: {calc.eu_per_tick():.5f} EU/t\n"
        f"Total Eu per Tick: {calc.eu_per_tick() * R_to_T:.5f} EU\n"
        f"Total Milliom Eu per tick: {(calc.eu_per_tick() * R_to_T)/1000000:.5f} M EU\n"
        f"Recipe Time: {calc.Recipe_time():.5f} s\n"
        f"Reactors → Turbine Ratio: {calc.Reactor_to_turbine_ratio():.5f}"

    )
    turbine_output_box.config(state="disabled")

root = tk.Tk()

root.title("Fusion Reactor To Plasma Turbine Ratio Calculator")
root.geometry("700x500")

#Plasma turbine recipe selector
Plasma_turbine_recipe_box = ttk.Combobox(
    root,
    values=[p.Plasma_type1 for p in Plasma_turbine_Recipes],
    state="readonly",
    width=25
)

#Rotor holder selector
Rotor_holder_box = ttk.Combobox(
    root,
    values=[t.Tier_name for t in Turbine_rotor_holder_tiers],
    state="readonly",
    width=10
)

#Turbine rotor selector
Turbine_rotor_box = ttk.Combobox(
    root,
    values=[r.Rotor_type for r in Turbine_rotor],
    state="readonly",
    width=25
)

reactor_amount = tk.IntVar(value=1)
Overclock_voltage = tk.IntVar(value=1)

tk.Label(root, text="Made By Minecrafrpro2039").place(x=0, y=0)
tk.Label(root, text="Number of Reactors:").place(x=10, y=25)
tk.Label(root, text="Plasma Turbine Recipes:").place(x=10, y=80)
tk.Label(root, text="Rotor Holder Hatch:").place(x=10, y=140)
tk.Label(root, text="Turbine Rotor:").place(x=10, y=200)

tk.Spinbox(root, from_=1, to=100, textvariable=reactor_amount,
           command=update_display, width=10).place(x=10, y=50)

reactor_output_box = tk.Text(root, width=75, height=15, state="disabled")
reactor_output_box.place(x=200, y=20)

turbine_output_box = tk.Text(root, width=75, height=15, state="disabled")
turbine_output_box.place(x=200, y=210)


Plasma_turbine_recipe_box.current(0)
Plasma_turbine_recipe_box.bind("<<ComboboxSelected>>", update_display)
Plasma_turbine_recipe_box.place(x=10, y=110)

Rotor_holder_box.current(0)
Rotor_holder_box.bind("<<ComboboxSelected>>", update_display)
Rotor_holder_box.place(x=10, y=170)

Turbine_rotor_box.current(0)
Turbine_rotor_box.bind("<<ComboboxSelected>>", update_display)
Turbine_rotor_box.place(x=10, y=230)

voltage_tier_label = tk.Label(root, text="Reactor Recipe Voltage Tier: N/A")
voltage_tier_label.place(x=10, y=260)
tk.Label(root, text= "If Reactor Reacipe is overclocked,\n increase the number in the\n spinbox below to decrease\n the Reactor recipe duration").place(x=10, y=280)
tk.Spinbox(root, from_=0, to=12, textvariable=Overclock_voltage,command=update_display, width=10).place(x=10, y=350)



update_display()
root.mainloop()

